export { UglyTracesSolver, checkUglyTraces } from "./ugly-traces-solver"
export { renderUglyTraceFinding } from "./render-finding"
export { writeUglyTracesReport } from "./write-report"
export type { CheckInput, CheckOptions, UglyTraceFinding } from "./types"
export { detectNon45DegreeSegments } from "./detect-non-45-degree-segments"
